


Resources:  
  WebServerGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: !GetAZs ''
      LaunchConfigurationName: !Ref LaunchConfig
      MinSize: '1'
      MaxSize: '3'
      TargetGroupARNs": [!Ref 'ALBTargetGroup']
     # LoadBalancerNames: [!Ref 'ApplicationLoadBalancer']


  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration    
    Properties:
      KeyName: latest
      ImageId:  ami-04b9e92b5572fa0d1 
      SecurityGroups: 
        - sg-06ec992117255b7cc
      InstanceType: t2.micro


  WebServerScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref 'WebServerGroup'
      Cooldown: '60'
      ScalingAdjustment: 1
  WebServerScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref 'WebServerGroup'
      Cooldown: '60'
      ScalingAdjustment: -1





  EC2TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: EC2TargetGroup
      Port: 80
      Protocol: HTTP
      Targets:
        - Id: i-0e07d971e4ff370f2
        - Id: i-04bd60ac683aa94f9
      Port: 80
      VpcId: vpc-05e99f3bca6bdf597

    #ELB (ALB)
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: EC2TargetGroup
      LoadBalancerArn:
          Ref: ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing # or internal
      Subnets:
        - subnet-0e33addbb4b146c6d
        - subnet-043d4b6880716276c
    #    SecurityGroupIds: 
    #      - sg-02337e68ba095af32







