AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AMI:
    Type: String
    Default: 'ami-02d55cb47e83a99a0'
  Subneta:
    Type: CommaDelimitedList
    Default: 'subnet-168aff5a'
  Subnetb:
    Type: CommaDelimitedList
    Default: 'subnet-b15ee1ca'
  VPC:
    Type: String
    Default: 'vpc-a50b15cd'
  
  InstanceTypeParameter:
    Type: String
    Default: 't2.micro'
Resources:
  Ec2Instance1:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      SecurityGroupIds: 
        - sg-0484a55f535e97f30
      KeyName: ramcharan
      ImageId: !Ref AMI
      SubnetId: !Ref Subneta
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash -xe
            sudo yum update -y
            sudo yum install nginx -y
            sudo service start nginx
            mkdir ravi

  Ec2Instance2:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      SecurityGroupIds: 
        - sg-0484a55f535e97f30
      KeyName: ramcharan
      ImageId: !Ref AMI
 #     AssociatePublicIpAddres: true
      SubnetId: !Ref Subnetb
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash -xe
            sudo yum update -y
            sudo yum install nginx -y
            sudo service nginx start
            mkdir ravi

  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: tar-group
      TargetType: instance
      Targets:
        - Id:  !Ref Ec2Instance1
        - Id:  !Ref Ec2Instance2
      VpcId: vpc-05e99f3bca6bdf597
      Port: 80
      Protocol: HTTP

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
         - subnet-0e33addbb4b146c6d
         - subnet-043d4b6880716276c
      SecurityGroups:
         - sg-072d8d87016e861d7

  Loadlistener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref DefaultTargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP


